# Generated by Django 3.0.2 on 2020-01-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200126_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
