# Generated by Django 3.0.2 on 2020-02-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_rating_qna', '0002_auto_20200131_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='q_n_a',
            name='answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
