# Generated by Django 3.0.2 on 2020-02-11 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_or_single', models.CharField(blank=True, max_length=6, null=True)),
                ('size', models.CharField(blank=True, max_length=7, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_datas', to='addresses.Address')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_datas', to='products.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_datas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
