# Generated by Django 3.0.2 on 2020-02-05 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_delete_homeeditableproduct'),
        ('addresses', '0003_auto_20200205_2220'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_datas', to='addresses.Address'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_datas', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_datas', to=settings.AUTH_USER_MODEL),
        ),
    ]
