# Generated by Django 3.0.2 on 2020-02-03 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_delete_homeeditableproduct'),
        ('cart', '0002_auto_20200121_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.Product'),
        ),
    ]
