# Generated by Django 3.0.2 on 2020-02-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditableProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.IntegerField(default=0)),
                ('color', models.CharField(default='white', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='editable_product_images/')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='T-shirt', max_length=100)),
                ('product_type', models.CharField(default='tshirt', max_length=15)),
                ('product_color', models.CharField(default='white', max_length=15)),
                ('product_design_type', models.CharField(default='plain', max_length=30)),
                ('search_kw', models.TextField(blank=True, null=True)),
                ('original_price', models.IntegerField(default=0)),
                ('seller_discount', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
