# Generated by Django 3.0.2 on 2020-01-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditableProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.IntegerField(default=0)),
                ('color', models.CharField(default='white', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='editable_product_images/')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='T-shirt', max_length=100)),
                ('original_price', models.IntegerField(default=0)),
                ('seller_discount', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
