# Generated by Django 3.0.2 on 2020-01-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editableproduct',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
