# Generated by Django 3.0.2 on 2020-02-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200223_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_design_type',
        ),
    ]
