# Generated by Django 3.0.2 on 2020-02-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_product_design_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tshirt', serialize=False, to='products.Product')),
                ('product_design_type', models.CharField(default='plain', max_length=30)),
            ],
        ),
    ]
