# Generated by Django 3.0.2 on 2020-02-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_tshirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='editableproduct',
            name='product_design_type',
            field=models.CharField(default='plain', max_length=30),
        ),
        migrations.DeleteModel(
            name='Tshirt',
        ),
    ]
