# Generated by Django 3.0.2 on 2020-02-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200226_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_design_type',
            field=models.CharField(default='plain', max_length=30),
        ),
    ]
