# Generated by Django 3.0.2 on 2020-01-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_homeeditableproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeeditableproduct',
            name='name',
            field=models.CharField(default='Blue T-shirt', max_length=100),
        ),
    ]
