# Generated by Django 3.0.2 on 2020-01-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_homeeditableproduct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(default='white', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='product_design_type',
            field=models.CharField(default='logic', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='tshirt', max_length=15),
        ),
    ]
