# Generated by Django 3.0.2 on 2020-01-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200127_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_design_type',
            field=models.CharField(default='plain', max_length=30),
        ),
    ]
