# Generated by Django 3.0.2 on 2020-01-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200127_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_kw',
            field=models.TextField(blank=True, null=True),
        ),
    ]
