# Generated by Django 3.0.2 on 2020-01-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_search_kw'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='XS S M L XL', max_length=20),
        ),
    ]
