# Generated by Django 3.0.2 on 2020-01-28 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeAndQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XXXL', 'XXXL'), ('XXL', 'XXL'), ('XL', 'XL'), ('M', 'M'), ('S', 'S'), ('XS', 'XS'), ('XXS', 'XXS'), ('XXXS', 'XXXS')], default='M', max_length=7)),
                ('quantity', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(default=62, on_delete=django.db.models.deletion.CASCADE, related_name='size_n_quan', to='products.Product')),
            ],
        ),
    ]
