# Generated by Django 3.0.2 on 2020-01-28 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_sizeandquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
