# Generated by Django 3.0.2 on 2020-01-28 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeandquantity',
            name='product',
            field=models.ForeignKey(default=62, on_delete=django.db.models.deletion.CASCADE, related_name='size_n_quantity', to='products.Product'),
        ),
    ]
