# Generated by Django 3.0.2 on 2020-01-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20200128_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeandquantity',
            name='size',
            field=models.CharField(choices=[('XXXL', 'XXXL'), ('XXL', 'XXL'), ('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S'), ('XS', 'XS'), ('XXS', 'XXS'), ('XXXS', 'XXXS')], default='M', max_length=7),
        ),
    ]
