# Generated by Django 3.0.2 on 2020-01-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200128_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeandquantity',
            name='quantity',
            field=models.IntegerField(default=5),
        ),
    ]
