# Generated by Django 3.0.2 on 2020-01-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200129_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeandquantity',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='sizeandquantity',
            name='ordering',
            field=models.IntegerField(default=6),
        ),
    ]
