# Generated by Django 3.0.2 on 2020-01-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200130_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeandquantity',
            name='ordering',
        ),
    ]
