# Generated by Django 3.0.2 on 2020-01-31 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_sizeandquantity_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='Fabric', max_length=15)),
                ('value', models.CharField(default='Cotton blend', max_length=15)),
                ('product', models.ForeignKey(default=62, on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='products.Product')),
            ],
        ),
    ]
