# Generated by Django 3.0.2 on 2020-01-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_productdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='value',
            field=models.CharField(default='Cotton blend', max_length=40),
        ),
    ]
