# Generated by Django 3.0.2 on 2020-01-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20200131_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='value',
            field=models.CharField(default='Cotton blend', max_length=50),
        ),
    ]
