# Generated by Django 3.0.2 on 2020-01-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizeandquantity',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.DeleteModel(
            name='SizeAndQuantity',
        ),
    ]
