# Generated by Django 3.0.2 on 2020-02-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200131_1721'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeEditableProduct',
        ),
    ]
