# Generated by Django 3.0.2 on 2020-02-11 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentOrder',
            fields=[
                ('order_id', models.CharField(blank=True, max_length=120, primary_key=True, serialize=False)),
                ('current_user', models.ForeignKey(default=62, on_delete=django.db.models.deletion.CASCADE, related_name='parent_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('quantity', models.IntegerField(default=1)),
                ('original_price', models.IntegerField(default=0)),
                ('seller_discount', models.IntegerField(default=0)),
                ('shipping_charges', models.IntegerField(default=0)),
                ('delivery_status', models.CharField(default='Yet to be approved', max_length=25)),
                ('order_datetime', models.DateTimeField(auto_now_add=True)),
                ('delivery_datetime', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_order', to='addresses.Address')),
                ('current_user', models.ForeignKey(default=62, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='products.Product')),
            ],
        ),
    ]
