# Generated by Django 3.0.2 on 2020-02-11 10:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='children_orders', to='orders.ParentOrder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentorder',
            name='order_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
