# Generated by Django 3.0.2 on 2020-02-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200211_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='parent_order',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_orders', to='orders.ParentOrder'),
        ),
    ]
