# Generated by Django 3.0.2 on 2020-01-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200121_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='current_user',
        ),
    ]
