# Generated by Django 3.0.2 on 2020-02-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_parent_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='original_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller_discount',
        ),
    ]
