# Generated by Django 3.0.2 on 2020-01-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200121_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default='Delivered', max_length=15),
        ),
    ]
