# Generated by Django 3.0.2 on 2020-02-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200223_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_discount',
            field=models.IntegerField(default=0),
        ),
    ]
