# Generated by Django 3.0.2 on 2020-01-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_applied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charges',
            field=models.IntegerField(default=0),
        ),
    ]
