# Generated by Django 3.0.2 on 2020-01-22 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200122_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_date',
            new_name='delivery_datetime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='order_datetime',
        ),
    ]
