# Generated by Django 3.0.2 on 2020-02-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_returnreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnreason',
            name='reason',
            field=models.CharField(default='Order placed by mistake', max_length=40),
        ),
    ]
