# Generated by Django 3.0.2 on 2020-02-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200224_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default='Ordered', max_length=25),
        ),
    ]
