# Generated by Django 3.0.2 on 2020-02-03 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200131_1721'),
        ('addresses', '0002_auto_20200122_1128'),
        ('orders', '0011_auto_20200122_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_order', to='addresses.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='products.Product'),
        ),
    ]
