# Generated by Django 3.0.2 on 2020-02-07 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200203_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='offer_applied',
            new_name='original_price',
        ),
        migrations.AddField(
            model_name='order',
            name='seller_discount',
            field=models.IntegerField(default=0),
        ),
    ]
