# Generated by Django 3.0.2 on 2020-02-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200207_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default='Yet to be approved', max_length=25),
        ),
    ]
