# Generated by Django 3.0.2 on 2020-01-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0023_auto_20200131_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeAndQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XXXL', 'XXXL'), ('XXL', 'XXL'), ('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S'), ('XS', 'XS'), ('XXS', 'XXS'), ('XXXS', 'XXXS')], default='M', max_length=7)),
                ('quantity', models.IntegerField(default=5)),
                ('product', models.ForeignKey(default=62, on_delete=django.db.models.deletion.CASCADE, related_name='size_n_quantity', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(default='Fabric', max_length=15)),
                ('value', models.CharField(default='Cotton blend', max_length=50)),
                ('product', models.ForeignKey(default=62, on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='products.Product')),
            ],
        ),
    ]
