# Generated by Django 3.0.2 on 2020-02-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
